import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.util.*;
import java.awt.event.*;
import java.awt.print.PrinterException;
import java.awt.print.*;
public class Invoice extends javax.swing.JFrame{
    String cName; 
    Boolean cNamec = false;
    static Hashtable<Integer,Invoice> shop = new Hashtable<Integer,Invoice>();
    static String csvFile = "C:/Users/Raj/Desktop/12.csv"; 
    static BufferedReader br = null;
    static String line = "" ;
    static String cvsSplitBy = "," ;
    static int id=0;
    String name,unit;
    float price;
    private static float totalPrice=0;
    
    public Invoice(String name1 , String unit1 , Float price1) {
        
        this.name=name1;
        this.unit=unit1;
        this.price=price1;
    }
    public Invoice() {
        initComponents();
          quantity.addKeyListener(new KeyAdapter(){
           public void keyPressed(KeyEvent e)
                   {
                       if((e.getKeyChar() >= '0' && e.getKeyChar() <='9')|| e.getKeyChar() == 32 ||e.getKeyChar() == 8 )
                        {
                            quantity.setEditable(true);
                        }
                   else{
                           quantity.setEditable(false);
                       }
                   }
           });
           tfTotalPrice.setEditable(false);
          billArea.setText(" *******************************************************\n ********************  YourMart   **********************\n *******************************************************\n");
          billArea.append("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        recieptPanel = new javax.swing.JPanel();
        print = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        billArea = new javax.swing.JTextArea();
        footerReciept = new javax.swing.JPanel();
        headerReciept = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        generatorPanel = new javax.swing.JPanel();
        quantityL = new javax.swing.JLabel();
        cname = new javax.swing.JTextField();
        quantity = new javax.swing.JTextField();
        customer = new javax.swing.JLabel();
        itName = new javax.swing.JLabel();
        itemName = new javax.swing.JTextField();
        headerInvoice = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        reset = new javax.swing.JButton();
        addItem = new javax.swing.JButton();
        footerInvoice = new javax.swing.JPanel();
        totalPricel = new javax.swing.JLabel();
        tfTotalPrice = new javax.swing.JTextField();
        total = new javax.swing.JButton();
        quantityLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Invoice Generator");
        setBackground(new java.awt.Color(204, 204, 204));

        recieptPanel.setBackground(new java.awt.Color(255, 255, 255));
        recieptPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        print.setBackground(new java.awt.Color(51, 102, 255));
        print.setForeground(new java.awt.Color(255, 255, 255));
        print.setText("Print");
        print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printActionPerformed(evt);
            }
        });

        billArea.setColumns(20);
        billArea.setRows(5);
        billArea.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jScrollPane3.setViewportView(billArea);

        footerReciept.setBackground(new java.awt.Color(51, 102, 255));
        footerReciept.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        footerReciept.setPreferredSize(new java.awt.Dimension(0, 18));

        javax.swing.GroupLayout footerRecieptLayout = new javax.swing.GroupLayout(footerReciept);
        footerReciept.setLayout(footerRecieptLayout);
        footerRecieptLayout.setHorizontalGroup(
            footerRecieptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        footerRecieptLayout.setVerticalGroup(
            footerRecieptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 15, Short.MAX_VALUE)
        );

        headerReciept.setBackground(new java.awt.Color(51, 102, 255));
        headerReciept.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("            Bill");

        javax.swing.GroupLayout headerRecieptLayout = new javax.swing.GroupLayout(headerReciept);
        headerReciept.setLayout(headerRecieptLayout);
        headerRecieptLayout.setHorizontalGroup(
            headerRecieptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        headerRecieptLayout.setVerticalGroup(
            headerRecieptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout recieptPanelLayout = new javax.swing.GroupLayout(recieptPanel);
        recieptPanel.setLayout(recieptPanelLayout);
        recieptPanelLayout.setHorizontalGroup(
            recieptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(recieptPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(footerReciept, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE)
            .addComponent(headerReciept, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, recieptPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(print, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        recieptPanelLayout.setVerticalGroup(
            recieptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(recieptPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(headerReciept, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(recieptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(recieptPanelLayout.createSequentialGroup()
                        .addGap(366, 366, 366)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE))
                    .addGroup(recieptPanelLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jScrollPane3)
                        .addGap(18, 18, 18)))
                .addComponent(print, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(footerReciept, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        generatorPanel.setBackground(new java.awt.Color(255, 255, 255));
        generatorPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        quantityL.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        quantityL.setText("Quantity");

        cname.setMinimumSize(new java.awt.Dimension(7, 22));
        cname.setPreferredSize(new java.awt.Dimension(60, 22));
        cname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cnameActionPerformed(evt);
            }
        });
        cname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cnameKeyPressed(evt);
            }
        });

        quantity.setMinimumSize(new java.awt.Dimension(7, 22));
        quantity.setPreferredSize(new java.awt.Dimension(60, 22));
        quantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantityActionPerformed(evt);
            }
        });
        quantity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                quantityKeyPressed(evt);
            }
        });

        customer.setBackground(new java.awt.Color(255, 255, 255));
        customer.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        customer.setText("Customer Name");

        itName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        itName.setText("Item Name");

        itemName.setMinimumSize(new java.awt.Dimension(7, 22));
        itemName.setPreferredSize(new java.awt.Dimension(60, 22));
        itemName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemNameActionPerformed(evt);
            }
        });
        itemName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                itemNameKeyPressed(evt);
            }
        });

        headerInvoice.setBackground(new java.awt.Color(51, 102, 255));
        headerInvoice.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setBackground(new java.awt.Color(255, 51, 0));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("           Invoice Generation");
        jLabel1.setAlignmentX(0.5F);
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout headerInvoiceLayout = new javax.swing.GroupLayout(headerInvoice);
        headerInvoice.setLayout(headerInvoiceLayout);
        headerInvoiceLayout.setHorizontalGroup(
            headerInvoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerInvoiceLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        headerInvoiceLayout.setVerticalGroup(
            headerInvoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
        );

        reset.setBackground(new java.awt.Color(51, 102, 255));
        reset.setForeground(new java.awt.Color(255, 255, 255));
        reset.setText("RESET");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });

        addItem.setBackground(new java.awt.Color(51, 102, 255));
        addItem.setForeground(new java.awt.Color(255, 255, 255));
        addItem.setText("ADD");
        addItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addItemActionPerformed(evt);
            }
        });

        footerInvoice.setBackground(new java.awt.Color(51, 102, 255));
        footerInvoice.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout footerInvoiceLayout = new javax.swing.GroupLayout(footerInvoice);
        footerInvoice.setLayout(footerInvoiceLayout);
        footerInvoiceLayout.setHorizontalGroup(
            footerInvoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        footerInvoiceLayout.setVerticalGroup(
            footerInvoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 15, Short.MAX_VALUE)
        );

        totalPricel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        totalPricel.setText("Total Price");

        tfTotalPrice.setMinimumSize(new java.awt.Dimension(7, 22));
        tfTotalPrice.setPreferredSize(new java.awt.Dimension(60, 22));
        tfTotalPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTotalPriceActionPerformed(evt);
            }
        });

        total.setBackground(new java.awt.Color(51, 102, 255));
        total.setForeground(new java.awt.Color(255, 255, 255));
        total.setText("TOTAL");
        total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalActionPerformed(evt);
            }
        });

        quantityLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout generatorPanelLayout = new javax.swing.GroupLayout(generatorPanel);
        generatorPanel.setLayout(generatorPanelLayout);
        generatorPanelLayout.setHorizontalGroup(
            generatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(headerInvoice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(footerInvoice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(generatorPanelLayout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addGroup(generatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, generatorPanelLayout.createSequentialGroup()
                        .addComponent(totalPricel, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tfTotalPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, generatorPanelLayout.createSequentialGroup()
                        .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(76, 76, 76)
                        .addComponent(reset, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addItem, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(generatorPanelLayout.createSequentialGroup()
                        .addGroup(generatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, generatorPanelLayout.createSequentialGroup()
                                .addGroup(generatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(customer)
                                    .addComponent(itName, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(37, 37, 37))
                            .addGroup(generatorPanelLayout.createSequentialGroup()
                                .addComponent(quantityL, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(47, 47, 47)))
                        .addGroup(generatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(generatorPanelLayout.createSequentialGroup()
                                .addComponent(quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(quantityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(generatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(cname, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(itemName, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        generatorPanelLayout.setVerticalGroup(
            generatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(generatorPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(headerInvoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addGroup(generatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(customer, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(generatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(itName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(itemName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(generatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(quantityL, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(quantityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(generatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfTotalPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalPricel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(115, 115, 115)
                .addGroup(generatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reset, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addItem, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(footerInvoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(generatorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(recieptPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(generatorPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(recieptPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(5, 5, 5))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printActionPerformed
        
    }//GEN-LAST:event_printActionPerformed

    private void quantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantityActionPerformed
        
    }//GEN-LAST:event_quantityActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        billArea.setText("");
        cNamec=false;
    }//GEN-LAST:event_resetActionPerformed

    private void addItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addItemActionPerformed
          String itemN=itemName.getText();
          float fPriceN;
          float quantityN = Float.parseFloat(quantity.getText());
          Invoice e= new Invoice();
          for(id=0;id<39;)
          { id++;
           e = shop.get(id);
           
           if(!cNamec){
           cName = cname.getText();   
           billArea.append("Customer's Name:- "+ cName);
           billArea.append("\n\n                  Item      Quantity        Price");
           cNamec =true;       
            }
   
           if(itemN.equals(e.name))
           {
           fPriceN = quantityN * e.price;
          
           billArea.append("\n                  "+ itemN + "      " + quantityN + " " + e.unit + "        " + fPriceN);
           totalPrice +=fPriceN;
           
           tfTotalPrice.setText(String.valueOf(totalPrice));
           itemName.setText("");
           quantity.setText("");
           quantityLabel.setText("");
           }
           
        }              
    }//GEN-LAST:event_addItemActionPerformed

    private void tfTotalPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTotalPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTotalPriceActionPerformed

    private void totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalActionPerformed
billArea.append("\n\t\t" + totalPrice);        
    }//GEN-LAST:event_totalActionPerformed

    private void cnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cnameActionPerformed
        
    }//GEN-LAST:event_cnameActionPerformed

    private void itemNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemNameActionPerformed
   
         
        
        
            
  // TODO add your handling code here:
    }//GEN-LAST:event_itemNameActionPerformed

    private void itemNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_itemNameKeyPressed
        String itemN=itemName.getText();
        if (evt.getKeyCode()==KeyEvent.VK_ENTER) {
             
        Invoice e= new Invoice();
        for(id=0;id<39;)
        {   id++;
           e = shop.get(id);
           if(itemN.equals(e.name))
           {
           quantityLabel.setText(e.unit);
           quantity.requestFocus();
           }     
            }}
    }//GEN-LAST:event_itemNameKeyPressed

    private void cnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cnameKeyPressed
     
     if(evt.getKeyCode()==KeyEvent.VK_ENTER)
     {
     itemName.requestFocus();
     }
    }//GEN-LAST:event_cnameKeyPressed

    private void quantityKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_quantityKeyPressed
      if(evt.getKeyCode()==KeyEvent.VK_ENTER)
      {
      String itemN=itemName.getText();
          float fPriceN;
          float quantityN = Float.parseFloat(quantity.getText());
          Invoice e= new Invoice();
          for(id=0;id<39;)
          { id++;
           e = shop.get(id);
           
           if(!cNamec){
           cName = cname.getText();   
           billArea.append("Customer's Name:- "+ cName);
           billArea.append("\n\n                  Item      Quantity        Price");
           cNamec =true;       
            }
   
           if(itemN.equals(e.name))
           {
           fPriceN = quantityN * e.price;
          
           billArea.append("\n                  "+ itemN + "      " + quantityN + " " + e.unit + "        " + fPriceN);
           totalPrice +=fPriceN;
           
           tfTotalPrice.setText(String.valueOf(totalPrice));
           itemName.setText("");
           quantity.setText("");
           quantityLabel.setText("");
           itemName.requestFocus();
           }
           
        } 
      }
    }//GEN-LAST:event_quantityKeyPressed

    
    public static void fileRead(){
     try{
        br = new BufferedReader(new FileReader(csvFile));
        while((line = br.readLine()) != null)
        {   
            id++ ;
           String[] data=line.split(cvsSplitBy);
           Invoice item=new Invoice(data[0],data[1],Float.parseFloat(data[2]));
           
           shop.put(id, item);
          
}
        }
        catch(IOException e){
            e.printStackTrace();
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        fileRead();
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Invoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Invoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Invoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Invoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
       
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Invoice().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addItem;
    private javax.swing.JTextArea billArea;
    private javax.swing.JTextField cname;
    private javax.swing.JLabel customer;
    private javax.swing.JPanel footerInvoice;
    private javax.swing.JPanel footerReciept;
    private javax.swing.JPanel generatorPanel;
    private javax.swing.JPanel headerInvoice;
    private javax.swing.JPanel headerReciept;
    private javax.swing.JLabel itName;
    private javax.swing.JTextField itemName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JButton print;
    private javax.swing.JTextField quantity;
    private javax.swing.JLabel quantityL;
    private javax.swing.JLabel quantityLabel;
    private javax.swing.JPanel recieptPanel;
    private javax.swing.JButton reset;
    private javax.swing.JTextField tfTotalPrice;
    private javax.swing.JButton total;
    private javax.swing.JLabel totalPricel;
    // End of variables declaration//GEN-END:variables
   
}
